# Generated by Django 3.1.7 on 2021-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
