# Generated by Django 3.1.7 on 2021-03-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210313_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_date']},
        ),
    ]
