# Generated by Django 3.1.7 on 2021-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('R', 'rent'), ('S', 'sold'), ('A', 'available'), ('B', 'booked')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
