# Generated by Django 3.1.7 on 2021-02-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_description'),
        ('items', '0003_auto_20210225_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_address', to='addresses.address'),
        ),
    ]
