# Generated by Django 3.1.7 on 2021-03-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_date']},
        ),
    ]
