# Generated by Django 3.2.4 on 2021-06-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_create_by_tracker_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='check_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='webhook',
            field=models.URLField(null=True),
        ),
    ]
